server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 263519
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # nacos的service地址
        server-addr: localhost:8848
        # 该服务属于的cluster名称
        cluster-name: BJ
        #元数据 k-v形式去定义
        metadata:
          #自己的版本
          version: v1
          #调用目标微服务的版本
          target-version: v1
        # 命名空间做隔离 这是dev的
        #namespace: 80a433f7-255c-4acd-a25b-ad53c7aa1628
  application:
    # 服务名称用-而不是_
    name: user-center

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator里的info信息
info:
  app-name: spring-boot-demo
  author: hqd
  email: xxx@qq.com
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
server:
  tomcat:
    max-connections: 1000
    threads:
      max: 300