server:
  port: 8010

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 263519
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # nacos的service地址
        server-addr: localhost:8848
        # 该服务所属集群名称
        cluster-name: BJ
        #元数据 k-v形式去定义
        metadata:
          #自己的版本
          version: v1
          #调用目标微服务的版本
          target-version: v1
        # 命名空间做隔离
        #namespace: 80a433f7-255c-4acd-a25b-ad53c7aa1628
    # Sentinel配置
    sentinel:
      transport:
        # 指定Sentinel控制台的地址
        dashboard: localhost:8080
  application:
    # 表示本服务的名称
    name: content-center
  # 解决@FeignClient 中name重复的问题
  main:
    allow-bean-definition-overriding: true

# actuator配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator里的info信息
info:
  app-name: spring-boot-demo
  author: hqd
  email: xxx@qq.com

# ribbon配置
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# ribbon饥饿加载，避免第一次请求过慢
ribbon:
  eager-load:
    clients: user-center #添加用，分割

#修改某个包下生成的日志级别
logging:
  level:
    #per.hqd: debug
    # 配置Feign的日志级别，建立在UserCenterFeignClient的日志级别是debug的基础上的
    per.hqd.contentcenter.feignClient.UserCenterFeignClient: debug

# Fegin配置
feign:
  client:
    config:
      # 想调用的服务名
      default:
        loggerLevel: FULL
  # 使用httpclient去做请求
  httpclient:
    enabled: true
    # Feign的最大连接数
    max-connections: 200
    # Feign单个路径最大连接数,即调用同一个接口的同时存在连接数
    max-connections-per-route: 50

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
server:
  tomcat:
    max-connections: 1000
    threads:
      max: 300