server:
  port: 8010

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 263519
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # nacos的service地址
        server-addr: localhost:8848
        # 该服务所属集群名称
        cluster-name: BJ
  application:
    # 表示本服务的名称
    name: content-center
# actuator配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator里的info信息
info:
  app-name: spring-boot-demo
  author: hqd
  email: xxx@qq.com
# ribbon配置
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# ribbon饥饿加载，避免第一次请求过慢
ribbon:
  eager-load:
    clients: user-center #添加用，分割
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
server:
  tomcat:
    max-connections: 1000
    threads:
      max: 300